main: NewGame.cpp CurrentGame.cpp Player.cpp Opponent.cpp pokemon.cpp RandomPoke.cpp pokemonList.cpp GamePlay.cpp HuntPvP.cpp Battle.cpp Stage1Pokemon.cpp Stage2Pokemon.cpp PvP.cpp MasterPvP.cpp
	g++ NewGame.cpp CurrentGame.cpp Player.cpp Opponent.cpp pokemon.cpp RandomPoke.cpp pokemonList.cpp GamePlay.cpp HuntPvP.cpp Battle.cpp Stage1Pokemon.cpp Stage2Pokemon.cpp PvP.cpp MasterPvP.cpp -o main
run: 
	clear
	./main